! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_LANGEVIN_2D
USE ISO_FORTRAN_ENV , ONLY : REAL64
  USE ISO_FORTRAN_ENV, ONLY: INT64
  IMPLICIT NONE


CONTAINS


  ! Getter and setter for UNIQUECOORDS1.
  SUBROUTINE LANGEVIN_2D_GET_UNIQUECOORDS1(UNIQUECOORDS1_ALLOCATED, UNIQUECOORDS1_DIM_1, UNIQUECOORDS1_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: UNIQUECOORDS1
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: UNIQUECOORDS1_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: UNIQUECOORDS1_DIM_1
    INTEGER(KIND=INT64) :: UNIQUECOORDS1_LOCAL
    UNIQUECOORDS1_ALLOCATED = ALLOCATED(UNIQUECOORDS1)
    IF (.NOT. UNIQUECOORDS1_ALLOCATED) RETURN
    UNIQUECOORDS1_DIM_1 = SIZE(UNIQUECOORDS1, 1, KIND=INT64)
    UNIQUECOORDS1_LOCAL = LOC(UNIQUECOORDS1(1))
  END SUBROUTINE LANGEVIN_2D_GET_UNIQUECOORDS1
  SUBROUTINE LANGEVIN_2D_SET_UNIQUECOORDS1(UNIQUECOORDS1_DIM_1, UNIQUECOORDS1_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: UNIQUECOORDS1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: UNIQUECOORDS1_DIM_1
    REAL(KIND=REAL64), DIMENSION(UNIQUECOORDS1_DIM_1) :: UNIQUECOORDS1_LOCAL
    IF (ALLOCATED(UNIQUECOORDS1)) THEN
      DEALLOCATE(UNIQUECOORDS1)
    END IF
    ALLOCATE(UNIQUECOORDS1(1:UNIQUECOORDS1_DIM_1))
    UNIQUECOORDS1 = UNIQUECOORDS1_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_UNIQUECOORDS1

  ! Getter and setter for UNIQUECOORDS2.
  SUBROUTINE LANGEVIN_2D_GET_UNIQUECOORDS2(UNIQUECOORDS2_ALLOCATED, UNIQUECOORDS2_DIM_1, UNIQUECOORDS2_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: UNIQUECOORDS2
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: UNIQUECOORDS2_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: UNIQUECOORDS2_DIM_1
    INTEGER(KIND=INT64) :: UNIQUECOORDS2_LOCAL
    UNIQUECOORDS2_ALLOCATED = ALLOCATED(UNIQUECOORDS2)
    IF (.NOT. UNIQUECOORDS2_ALLOCATED) RETURN
    UNIQUECOORDS2_DIM_1 = SIZE(UNIQUECOORDS2, 1, KIND=INT64)
    UNIQUECOORDS2_LOCAL = LOC(UNIQUECOORDS2(1))
  END SUBROUTINE LANGEVIN_2D_GET_UNIQUECOORDS2
  SUBROUTINE LANGEVIN_2D_SET_UNIQUECOORDS2(UNIQUECOORDS2_DIM_1, UNIQUECOORDS2_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: UNIQUECOORDS2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: UNIQUECOORDS2_DIM_1
    REAL(KIND=REAL64), DIMENSION(UNIQUECOORDS2_DIM_1) :: UNIQUECOORDS2_LOCAL
    IF (ALLOCATED(UNIQUECOORDS2)) THEN
      DEALLOCATE(UNIQUECOORDS2)
    END IF
    ALLOCATE(UNIQUECOORDS2(1:UNIQUECOORDS2_DIM_1))
    UNIQUECOORDS2 = UNIQUECOORDS2_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_UNIQUECOORDS2

  ! Getter and setter for PES.
  SUBROUTINE LANGEVIN_2D_GET_PES(PES_ALLOCATED, PES_DIM_1, PES_DIM_2, PES_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: PES
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: PES_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: PES_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PES_DIM_2
    INTEGER(KIND=INT64) :: PES_LOCAL
    PES_ALLOCATED = ALLOCATED(PES)
    IF (.NOT. PES_ALLOCATED) RETURN
    PES_DIM_1 = SIZE(PES, 1, KIND=INT64)
    PES_DIM_2 = SIZE(PES, 2, KIND=INT64)
    PES_LOCAL = LOC(PES(1,1))
  END SUBROUTINE LANGEVIN_2D_GET_PES
  SUBROUTINE LANGEVIN_2D_SET_PES(PES_DIM_1, PES_DIM_2, PES_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: PES
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PES_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PES_DIM_2
    REAL(KIND=REAL64), DIMENSION(PES_DIM_1,PES_DIM_2) :: PES_LOCAL
    IF (ALLOCATED(PES)) THEN
      DEALLOCATE(PES)
    END IF
    ALLOCATE(PES(1:PES_DIM_1,1:PES_DIM_2))
    PES = PES_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_PES

  ! Getter and setter for NECKVALS.
  SUBROUTINE LANGEVIN_2D_GET_NECKVALS(NECKVALS_ALLOCATED, NECKVALS_DIM_1, NECKVALS_DIM_2, NECKVALS_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: NECKVALS
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: NECKVALS_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: NECKVALS_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: NECKVALS_DIM_2
    INTEGER(KIND=INT64) :: NECKVALS_LOCAL
    NECKVALS_ALLOCATED = ALLOCATED(NECKVALS)
    IF (.NOT. NECKVALS_ALLOCATED) RETURN
    NECKVALS_DIM_1 = SIZE(NECKVALS, 1, KIND=INT64)
    NECKVALS_DIM_2 = SIZE(NECKVALS, 2, KIND=INT64)
    NECKVALS_LOCAL = LOC(NECKVALS(1,1))
  END SUBROUTINE LANGEVIN_2D_GET_NECKVALS
  SUBROUTINE LANGEVIN_2D_SET_NECKVALS(NECKVALS_DIM_1, NECKVALS_DIM_2, NECKVALS_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: NECKVALS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NECKVALS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NECKVALS_DIM_2
    REAL(KIND=REAL64), DIMENSION(NECKVALS_DIM_1,NECKVALS_DIM_2) :: NECKVALS_LOCAL
    IF (ALLOCATED(NECKVALS)) THEN
      DEALLOCATE(NECKVALS)
    END IF
    ALLOCATE(NECKVALS(1:NECKVALS_DIM_1,1:NECKVALS_DIM_2))
    NECKVALS = NECKVALS_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_NECKVALS

  ! Getter and setter for PESGRAD.
  SUBROUTINE LANGEVIN_2D_GET_PESGRAD(PESGRAD_ALLOCATED, PESGRAD_DIM_1, PESGRAD_DIM_2, PESGRAD_DIM_3, PESGRAD_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: PESGRAD
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: PESGRAD_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: PESGRAD_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PESGRAD_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: PESGRAD_DIM_3
    INTEGER(KIND=INT64) :: PESGRAD_LOCAL
    PESGRAD_ALLOCATED = ALLOCATED(PESGRAD)
    IF (.NOT. PESGRAD_ALLOCATED) RETURN
    PESGRAD_DIM_1 = SIZE(PESGRAD, 1, KIND=INT64)
    PESGRAD_DIM_2 = SIZE(PESGRAD, 2, KIND=INT64)
    PESGRAD_DIM_3 = SIZE(PESGRAD, 3, KIND=INT64)
    PESGRAD_LOCAL = LOC(PESGRAD(1,1,1))
  END SUBROUTINE LANGEVIN_2D_GET_PESGRAD
  SUBROUTINE LANGEVIN_2D_SET_PESGRAD(PESGRAD_DIM_1, PESGRAD_DIM_2, PESGRAD_DIM_3, PESGRAD_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: PESGRAD
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESGRAD_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESGRAD_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESGRAD_DIM_3
    REAL(KIND=REAL64), DIMENSION(PESGRAD_DIM_1,PESGRAD_DIM_2,PESGRAD_DIM_3) :: PESGRAD_LOCAL
    IF (ALLOCATED(PESGRAD)) THEN
      DEALLOCATE(PESGRAD)
    END IF
    ALLOCATE(PESGRAD(1:PESGRAD_DIM_1,1:PESGRAD_DIM_2,1:PESGRAD_DIM_3))
    PESGRAD = PESGRAD_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_PESGRAD

  ! Getter and setter for PESHESS.
  SUBROUTINE LANGEVIN_2D_GET_PESHESS(PESHESS_ALLOCATED, PESHESS_DIM_1, PESHESS_DIM_2, PESHESS_DIM_3, PESHESS_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: PESHESS
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: PESHESS_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: PESHESS_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PESHESS_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: PESHESS_DIM_3
    INTEGER(KIND=INT64) :: PESHESS_LOCAL
    PESHESS_ALLOCATED = ALLOCATED(PESHESS)
    IF (.NOT. PESHESS_ALLOCATED) RETURN
    PESHESS_DIM_1 = SIZE(PESHESS, 1, KIND=INT64)
    PESHESS_DIM_2 = SIZE(PESHESS, 2, KIND=INT64)
    PESHESS_DIM_3 = SIZE(PESHESS, 3, KIND=INT64)
    PESHESS_LOCAL = LOC(PESHESS(1,1,1))
  END SUBROUTINE LANGEVIN_2D_GET_PESHESS
  SUBROUTINE LANGEVIN_2D_SET_PESHESS(PESHESS_DIM_1, PESHESS_DIM_2, PESHESS_DIM_3, PESHESS_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: PESHESS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESHESS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESHESS_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESHESS_DIM_3
    REAL(KIND=REAL64), DIMENSION(PESHESS_DIM_1,PESHESS_DIM_2,PESHESS_DIM_3) :: PESHESS_LOCAL
    IF (ALLOCATED(PESHESS)) THEN
      DEALLOCATE(PESHESS)
    END IF
    ALLOCATE(PESHESS(1:PESHESS_DIM_1,1:PESHESS_DIM_2,1:PESHESS_DIM_3))
    PESHESS = PESHESS_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_PESHESS

  ! Getter and setter for INVERSEMETRIC.
  SUBROUTINE LANGEVIN_2D_GET_INVERSEMETRIC(INVERSEMETRIC_ALLOCATED, INVERSEMETRIC_DIM_1, INVERSEMETRIC_DIM_2, INVERSEMETRIC_DIM_3, &
&INVERSEMETRIC_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: INVERSEMETRIC
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: INVERSEMETRIC_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRIC_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRIC_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRIC_DIM_3
    INTEGER(KIND=INT64) :: INVERSEMETRIC_LOCAL
    INVERSEMETRIC_ALLOCATED = ALLOCATED(INVERSEMETRIC)
    IF (.NOT. INVERSEMETRIC_ALLOCATED) RETURN
    INVERSEMETRIC_DIM_1 = SIZE(INVERSEMETRIC, 1, KIND=INT64)
    INVERSEMETRIC_DIM_2 = SIZE(INVERSEMETRIC, 2, KIND=INT64)
    INVERSEMETRIC_DIM_3 = SIZE(INVERSEMETRIC, 3, KIND=INT64)
    INVERSEMETRIC_LOCAL = LOC(INVERSEMETRIC(1,1,1))
  END SUBROUTINE LANGEVIN_2D_GET_INVERSEMETRIC
  SUBROUTINE LANGEVIN_2D_SET_INVERSEMETRIC(INVERSEMETRIC_DIM_1, INVERSEMETRIC_DIM_2, INVERSEMETRIC_DIM_3, INVERSEMETRIC_LOCAL) BIND&
&(C)
    USE LANGEVIN_2D, ONLY: INVERSEMETRIC
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRIC_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRIC_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRIC_DIM_3
    REAL(KIND=REAL64), DIMENSION(INVERSEMETRIC_DIM_1,INVERSEMETRIC_DIM_2,INVERSEMETRIC_DIM_3) :: INVERSEMETRIC_LOCAL
    IF (ALLOCATED(INVERSEMETRIC)) THEN
      DEALLOCATE(INVERSEMETRIC)
    END IF
    ALLOCATE(INVERSEMETRIC(1:INVERSEMETRIC_DIM_1,1:INVERSEMETRIC_DIM_2,1:INVERSEMETRIC_DIM_3))
    INVERSEMETRIC = INVERSEMETRIC_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_INVERSEMETRIC

  ! Getter and setter for INVERSEMETRICGRAD.
  SUBROUTINE LANGEVIN_2D_GET_INVERSEMETRICGRAD(INVERSEMETRICGRAD_ALLOCATED, INVERSEMETRICGRAD_DIM_1, INVERSEMETRICGRAD_DIM_2, INVER&
&SEMETRICGRAD_DIM_3, INVERSEMETRICGRAD_DIM_4, INVERSEMETRICGRAD_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: INVERSEMETRICGRAD
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: INVERSEMETRICGRAD_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICGRAD_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICGRAD_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICGRAD_DIM_3
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICGRAD_DIM_4
    INTEGER(KIND=INT64) :: INVERSEMETRICGRAD_LOCAL
    INVERSEMETRICGRAD_ALLOCATED = ALLOCATED(INVERSEMETRICGRAD)
    IF (.NOT. INVERSEMETRICGRAD_ALLOCATED) RETURN
    INVERSEMETRICGRAD_DIM_1 = SIZE(INVERSEMETRICGRAD, 1, KIND=INT64)
    INVERSEMETRICGRAD_DIM_2 = SIZE(INVERSEMETRICGRAD, 2, KIND=INT64)
    INVERSEMETRICGRAD_DIM_3 = SIZE(INVERSEMETRICGRAD, 3, KIND=INT64)
    INVERSEMETRICGRAD_DIM_4 = SIZE(INVERSEMETRICGRAD, 4, KIND=INT64)
    INVERSEMETRICGRAD_LOCAL = LOC(INVERSEMETRICGRAD(1,1,1,1))
  END SUBROUTINE LANGEVIN_2D_GET_INVERSEMETRICGRAD
  SUBROUTINE LANGEVIN_2D_SET_INVERSEMETRICGRAD(INVERSEMETRICGRAD_DIM_1, INVERSEMETRICGRAD_DIM_2, INVERSEMETRICGRAD_DIM_3, INVERSEME&
&TRICGRAD_DIM_4, INVERSEMETRICGRAD_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: INVERSEMETRICGRAD
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICGRAD_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICGRAD_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICGRAD_DIM_3
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICGRAD_DIM_4
    REAL(KIND=REAL64), DIMENSION(INVERSEMETRICGRAD_DIM_1,INVERSEMETRICGRAD_DIM_2,INVERSEMETRICGRAD_DIM_3,INVERSEMETRICGRAD_DIM_4) :&
&: INVERSEMETRICGRAD_LOCAL
    IF (ALLOCATED(INVERSEMETRICGRAD)) THEN
      DEALLOCATE(INVERSEMETRICGRAD)
    END IF
    ALLOCATE(INVERSEMETRICGRAD(1:INVERSEMETRICGRAD_DIM_1,1:INVERSEMETRICGRAD_DIM_2,1:INVERSEMETRICGRAD_DIM_3,1:INVERSEMETRICGRAD_DI&
&M_4))
    INVERSEMETRICGRAD = INVERSEMETRICGRAD_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_INVERSEMETRICGRAD

  ! Getter and setter for INVERSEMETRICHESS.
  SUBROUTINE LANGEVIN_2D_GET_INVERSEMETRICHESS(INVERSEMETRICHESS_ALLOCATED, INVERSEMETRICHESS_DIM_1, INVERSEMETRICHESS_DIM_2, INVER&
&SEMETRICHESS_DIM_3, INVERSEMETRICHESS_DIM_4, INVERSEMETRICHESS_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: INVERSEMETRICHESS
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: INVERSEMETRICHESS_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICHESS_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICHESS_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICHESS_DIM_3
    INTEGER(KIND=INT64), INTENT(OUT) :: INVERSEMETRICHESS_DIM_4
    INTEGER(KIND=INT64) :: INVERSEMETRICHESS_LOCAL
    INVERSEMETRICHESS_ALLOCATED = ALLOCATED(INVERSEMETRICHESS)
    IF (.NOT. INVERSEMETRICHESS_ALLOCATED) RETURN
    INVERSEMETRICHESS_DIM_1 = SIZE(INVERSEMETRICHESS, 1, KIND=INT64)
    INVERSEMETRICHESS_DIM_2 = SIZE(INVERSEMETRICHESS, 2, KIND=INT64)
    INVERSEMETRICHESS_DIM_3 = SIZE(INVERSEMETRICHESS, 3, KIND=INT64)
    INVERSEMETRICHESS_DIM_4 = SIZE(INVERSEMETRICHESS, 4, KIND=INT64)
    INVERSEMETRICHESS_LOCAL = LOC(INVERSEMETRICHESS(1,1,1,1))
  END SUBROUTINE LANGEVIN_2D_GET_INVERSEMETRICHESS
  SUBROUTINE LANGEVIN_2D_SET_INVERSEMETRICHESS(INVERSEMETRICHESS_DIM_1, INVERSEMETRICHESS_DIM_2, INVERSEMETRICHESS_DIM_3, INVERSEME&
&TRICHESS_DIM_4, INVERSEMETRICHESS_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: INVERSEMETRICHESS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICHESS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICHESS_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICHESS_DIM_3
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVERSEMETRICHESS_DIM_4
    REAL(KIND=REAL64), DIMENSION(INVERSEMETRICHESS_DIM_1,INVERSEMETRICHESS_DIM_2,INVERSEMETRICHESS_DIM_3,INVERSEMETRICHESS_DIM_4) :&
&: INVERSEMETRICHESS_LOCAL
    IF (ALLOCATED(INVERSEMETRICHESS)) THEN
      DEALLOCATE(INVERSEMETRICHESS)
    END IF
    ALLOCATE(INVERSEMETRICHESS(1:INVERSEMETRICHESS_DIM_1,1:INVERSEMETRICHESS_DIM_2,1:INVERSEMETRICHESS_DIM_3,1:INVERSEMETRICHESS_DI&
&M_4))
    INVERSEMETRICHESS = INVERSEMETRICHESS_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_INVERSEMETRICHESS

  ! Getter and setter for FRICTION.
  SUBROUTINE LANGEVIN_2D_GET_FRICTION(FRICTION_ALLOCATED, FRICTION_DIM_1, FRICTION_DIM_2, FRICTION_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: FRICTION
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: FRICTION_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: FRICTION_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: FRICTION_DIM_2
    INTEGER(KIND=INT64) :: FRICTION_LOCAL
    FRICTION_ALLOCATED = ALLOCATED(FRICTION)
    IF (.NOT. FRICTION_ALLOCATED) RETURN
    FRICTION_DIM_1 = SIZE(FRICTION, 1, KIND=INT64)
    FRICTION_DIM_2 = SIZE(FRICTION, 2, KIND=INT64)
    FRICTION_LOCAL = LOC(FRICTION(1,1))
  END SUBROUTINE LANGEVIN_2D_GET_FRICTION
  SUBROUTINE LANGEVIN_2D_SET_FRICTION(FRICTION_DIM_1, FRICTION_DIM_2, FRICTION_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: FRICTION
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FRICTION_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FRICTION_DIM_2
    REAL(KIND=REAL64), DIMENSION(FRICTION_DIM_1,FRICTION_DIM_2) :: FRICTION_LOCAL
    IF (ALLOCATED(FRICTION)) THEN
      DEALLOCATE(FRICTION)
    END IF
    ALLOCATE(FRICTION(1:FRICTION_DIM_1,1:FRICTION_DIM_2))
    FRICTION = FRICTION_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_FRICTION

  ! Getter and setter for RANDOMFORCE.
  SUBROUTINE LANGEVIN_2D_GET_RANDOMFORCE(RANDOMFORCE_ALLOCATED, RANDOMFORCE_DIM_1, RANDOMFORCE_DIM_2, RANDOMFORCE_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: RANDOMFORCE
    LOGICAL(KIND=C_BOOL), INTENT(OUT) :: RANDOMFORCE_ALLOCATED
    INTEGER(KIND=INT64), INTENT(OUT) :: RANDOMFORCE_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: RANDOMFORCE_DIM_2
    INTEGER(KIND=INT64) :: RANDOMFORCE_LOCAL
    RANDOMFORCE_ALLOCATED = ALLOCATED(RANDOMFORCE)
    IF (.NOT. RANDOMFORCE_ALLOCATED) RETURN
    RANDOMFORCE_DIM_1 = SIZE(RANDOMFORCE, 1, KIND=INT64)
    RANDOMFORCE_DIM_2 = SIZE(RANDOMFORCE, 2, KIND=INT64)
    RANDOMFORCE_LOCAL = LOC(RANDOMFORCE(1,1))
  END SUBROUTINE LANGEVIN_2D_GET_RANDOMFORCE
  SUBROUTINE LANGEVIN_2D_SET_RANDOMFORCE(RANDOMFORCE_DIM_1, RANDOMFORCE_DIM_2, RANDOMFORCE_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: RANDOMFORCE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: RANDOMFORCE_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: RANDOMFORCE_DIM_2
    REAL(KIND=REAL64), DIMENSION(RANDOMFORCE_DIM_1,RANDOMFORCE_DIM_2) :: RANDOMFORCE_LOCAL
    IF (ALLOCATED(RANDOMFORCE)) THEN
      DEALLOCATE(RANDOMFORCE)
    END IF
    ALLOCATE(RANDOMFORCE(1:RANDOMFORCE_DIM_1,1:RANDOMFORCE_DIM_2))
    RANDOMFORCE = RANDOMFORCE_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_RANDOMFORCE

  ! Getter and setter for NGRIDPOINTS.
  SUBROUTINE LANGEVIN_2D_GET_NGRIDPOINTS(NGRIDPOINTS_DIM_1, NGRIDPOINTS_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE LANGEVIN_2D, ONLY: NGRIDPOINTS
    INTEGER(KIND=INT64), INTENT(OUT) :: NGRIDPOINTS_DIM_1
    INTEGER(KIND=INT64) :: NGRIDPOINTS_LOCAL
    NGRIDPOINTS_DIM_1 = SIZE(NGRIDPOINTS, 1, KIND=INT64)
    NGRIDPOINTS_LOCAL = LOC(NGRIDPOINTS(1))
  END SUBROUTINE LANGEVIN_2D_GET_NGRIDPOINTS
  SUBROUTINE LANGEVIN_2D_SET_NGRIDPOINTS(NGRIDPOINTS_DIM_1, NGRIDPOINTS_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: NGRIDPOINTS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NGRIDPOINTS_DIM_1
    INTEGER, DIMENSION(NGRIDPOINTS_DIM_1) :: NGRIDPOINTS_LOCAL
    NGRIDPOINTS = NGRIDPOINTS_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_NGRIDPOINTS

  ! Getter and setter for DX.
  SUBROUTINE LANGEVIN_2D_GET_DX(DX_DIM_1, DX_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE LANGEVIN_2D, ONLY: DX
    INTEGER(KIND=INT64), INTENT(OUT) :: DX_DIM_1
    INTEGER(KIND=INT64) :: DX_LOCAL
    DX_DIM_1 = SIZE(DX, 1, KIND=INT64)
    DX_LOCAL = LOC(DX(1))
  END SUBROUTINE LANGEVIN_2D_GET_DX
  SUBROUTINE LANGEVIN_2D_SET_DX(DX_DIM_1, DX_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: DX
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: DX_DIM_1
    REAL(KIND=REAL64), DIMENSION(DX_DIM_1) :: DX_LOCAL
    DX = DX_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_DX

  ! Getter and setter for MASSVAL.
  SUBROUTINE LANGEVIN_2D_GET_MASSVAL(MASSVAL_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: MASSVAL
    REAL(KIND=REAL64) :: MASSVAL_LOCAL
    MASSVAL_LOCAL = MASSVAL
  END SUBROUTINE LANGEVIN_2D_GET_MASSVAL
  SUBROUTINE LANGEVIN_2D_SET_MASSVAL(MASSVAL_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: MASSVAL
    REAL(KIND=REAL64) :: MASSVAL_LOCAL
    MASSVAL = MASSVAL_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_MASSVAL

  ! Getter and setter for STARTINGENEG.
  SUBROUTINE LANGEVIN_2D_GET_STARTINGENEG(STARTINGENEG_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: STARTINGENEG
    REAL(KIND=REAL64) :: STARTINGENEG_LOCAL
    STARTINGENEG_LOCAL = STARTINGENEG
  END SUBROUTINE LANGEVIN_2D_GET_STARTINGENEG
  SUBROUTINE LANGEVIN_2D_SET_STARTINGENEG(STARTINGENEG_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: STARTINGENEG
    REAL(KIND=REAL64) :: STARTINGENEG_LOCAL
    STARTINGENEG = STARTINGENEG_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_STARTINGENEG

  ! Getter and setter for DT.
  SUBROUTINE LANGEVIN_2D_GET_DT(DT_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: DT
    REAL(KIND=REAL64) :: DT_LOCAL
    DT_LOCAL = DT
  END SUBROUTINE LANGEVIN_2D_GET_DT
  SUBROUTINE LANGEVIN_2D_SET_DT(DT_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: DT
    REAL(KIND=REAL64) :: DT_LOCAL
    DT = DT_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_DT

  ! Getter and setter for MAXTIME.
  SUBROUTINE LANGEVIN_2D_GET_MAXTIME(MAXTIME_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: MAXTIME
    REAL(KIND=REAL64) :: MAXTIME_LOCAL
    MAXTIME_LOCAL = MAXTIME
  END SUBROUTINE LANGEVIN_2D_GET_MAXTIME
  SUBROUTINE LANGEVIN_2D_SET_MAXTIME(MAXTIME_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: MAXTIME
    REAL(KIND=REAL64) :: MAXTIME_LOCAL
    MAXTIME = MAXTIME_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_MAXTIME

  ! Getter and setter for SCISSIONNECKVAL.
  SUBROUTINE LANGEVIN_2D_GET_SCISSIONNECKVAL(SCISSIONNECKVAL_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: SCISSIONNECKVAL
    REAL(KIND=REAL64) :: SCISSIONNECKVAL_LOCAL
    SCISSIONNECKVAL_LOCAL = SCISSIONNECKVAL
  END SUBROUTINE LANGEVIN_2D_GET_SCISSIONNECKVAL
  SUBROUTINE LANGEVIN_2D_SET_SCISSIONNECKVAL(SCISSIONNECKVAL_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: SCISSIONNECKVAL
    REAL(KIND=REAL64) :: SCISSIONNECKVAL_LOCAL
    SCISSIONNECKVAL = SCISSIONNECKVAL_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_SCISSIONNECKVAL

  ! Getter and setter for LEVELDENSITY.
  SUBROUTINE LANGEVIN_2D_GET_LEVELDENSITY(LEVELDENSITY_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: LEVELDENSITY
    REAL(KIND=REAL64) :: LEVELDENSITY_LOCAL
    LEVELDENSITY_LOCAL = LEVELDENSITY
  END SUBROUTINE LANGEVIN_2D_GET_LEVELDENSITY
  SUBROUTINE LANGEVIN_2D_SET_LEVELDENSITY(LEVELDENSITY_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: LEVELDENSITY
    REAL(KIND=REAL64) :: LEVELDENSITY_LOCAL
    LEVELDENSITY = LEVELDENSITY_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_LEVELDENSITY

  ! Getter and setter for MAXITERS.
  SUBROUTINE LANGEVIN_2D_GET_MAXITERS(MAXITERS_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: MAXITERS
    INTEGER :: MAXITERS_LOCAL
    MAXITERS_LOCAL = MAXITERS
  END SUBROUTINE LANGEVIN_2D_GET_MAXITERS
  SUBROUTINE LANGEVIN_2D_SET_MAXITERS(MAXITERS_LOCAL) BIND(C)
    USE LANGEVIN_2D, ONLY: MAXITERS
    INTEGER :: MAXITERS_LOCAL
    MAXITERS = MAXITERS_LOCAL
  END SUBROUTINE LANGEVIN_2D_SET_MAXITERS

  
  SUBROUTINE C_SETUP_ARRAYS(UNCOORDS1IN_DIM_1, UNCOORDS1IN, UNCOORDS2IN_DIM_1, UNCOORDS2IN, PESIN_DIM_1, PESIN_DIM_2, PESIN, PESGRA&
&DIN_DIM_1, PESGRADIN_DIM_2, PESGRADIN_DIM_3, PESGRADIN, PESHESSIN_DIM_1, PESHESSIN_DIM_2, PESHESSIN_DIM_3, PESHESSIN, INVMETIN_DIM&
&_1, INVMETIN_DIM_2, INVMETIN_DIM_3, INVMETIN, INVMETGRADIN_DIM_1, INVMETGRADIN_DIM_2, INVMETGRADIN_DIM_3, INVMETGRADIN_DIM_4, INVM&
&ETGRADIN, INVMETHESSIN_DIM_1, INVMETHESSIN_DIM_2, INVMETHESSIN_DIM_3, INVMETHESSIN_DIM_4, INVMETHESSIN, FRICIN_DIM_1, FRICIN_DIM_2&
&, FRICIN, RANDFORCEIN_DIM_1, RANDFORCEIN_DIM_2, RANDFORCEIN, NECKIN_DIM_1, NECKIN_DIM_2, NECKIN) BIND(C)
    USE LANGEVIN_2D, ONLY: SETUP_ARRAYS
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: UNCOORDS1IN_DIM_1
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(UNCOORDS1IN_DIM_1) :: UNCOORDS1IN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: UNCOORDS2IN_DIM_1
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(UNCOORDS2IN_DIM_1) :: UNCOORDS2IN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESIN_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(PESIN_DIM_1,PESIN_DIM_2) :: PESIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESGRADIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESGRADIN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESGRADIN_DIM_3
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(PESGRADIN_DIM_1,PESGRADIN_DIM_2,PESGRADIN_DIM_3) :: PESGRADIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESHESSIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESHESSIN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PESHESSIN_DIM_3
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(PESHESSIN_DIM_1,PESHESSIN_DIM_2,PESHESSIN_DIM_3) :: PESHESSIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETIN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETIN_DIM_3
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(INVMETIN_DIM_1,INVMETIN_DIM_2,INVMETIN_DIM_3) :: INVMETIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETGRADIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETGRADIN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETGRADIN_DIM_3
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETGRADIN_DIM_4
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(INVMETGRADIN_DIM_1,INVMETGRADIN_DIM_2,INVMETGRADIN_DIM_3,INVMETGRADIN_DIM_4) :: INVMET&
&GRADIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETHESSIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETHESSIN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETHESSIN_DIM_3
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETHESSIN_DIM_4
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(INVMETHESSIN_DIM_1,INVMETHESSIN_DIM_2,INVMETHESSIN_DIM_3,INVMETHESSIN_DIM_4) :: INVMET&
&HESSIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FRICIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FRICIN_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(FRICIN_DIM_1,FRICIN_DIM_2) :: FRICIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: RANDFORCEIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: RANDFORCEIN_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(RANDFORCEIN_DIM_1,RANDFORCEIN_DIM_2) :: RANDFORCEIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NECKIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NECKIN_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(NECKIN_DIM_1,NECKIN_DIM_2) :: NECKIN
  
    CALL SETUP_ARRAYS(UNCOORDS1IN, UNCOORDS2IN, PESIN, PESGRADIN, PESHESSIN, INVMETIN, INVMETGRADIN, INVMETHESSIN, FRICIN, RANDFORC&
&EIN, NECKIN)
  END SUBROUTINE C_SETUP_ARRAYS
  

  
  SUBROUTINE C_SETUP_PARAMS(MASSVALIN, STARTINGENEGIN, DTIN, MAXTIMEIN, SCISSIONNECKVALIN, USESEED, SEED_DIM_1, SEED) BIND(C)
    USE LANGEVIN_2D, ONLY: SETUP_PARAMS
    IMPLICIT NONE
    REAL(KIND=REAL64), INTENT(IN) :: MASSVALIN
    REAL(KIND=REAL64), INTENT(IN) :: STARTINGENEGIN
    REAL(KIND=REAL64), INTENT(IN) :: DTIN
    REAL(KIND=REAL64), INTENT(IN) :: MAXTIMEIN
    REAL(KIND=REAL64), INTENT(IN) :: SCISSIONNECKVALIN
    LOGICAL, INTENT(IN) :: USESEED
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: SEED_DIM_1
    INTEGER, INTENT(IN), DIMENSION(SEED_DIM_1) :: SEED
  
    CALL SETUP_PARAMS(MASSVALIN, STARTINGENEGIN, DTIN, MAXTIMEIN, SCISSIONNECKVALIN, USESEED, SEED)
  END SUBROUTINE C_SETUP_PARAMS
  

  
  SUBROUTINE C_GET_INTERPOLATION_INDICES(COORDS_DIM_1, COORDS, IDX_DIM_1, IDX, ISOUTOFBOUNDS) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: GET_INTERPOLATION_INDICES
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: COORDS_DIM_1
    REAL(KIND=REAL64), INTENT(INOUT), DIMENSION(COORDS_DIM_1) :: COORDS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: IDX_DIM_1
    INTEGER, INTENT(OUT), DIMENSION(IDX_DIM_1) :: IDX
    LOGICAL, INTENT(OUT) :: ISOUTOFBOUNDS
  
    CALL GET_INTERPOLATION_INDICES(COORDS, IDX, ISOUTOFBOUNDS)
  END SUBROUTINE C_GET_INTERPOLATION_INDICES
  

  
  SUBROUTINE C_BILINEAR_INTERP(IDX_DIM_1, IDX, COORDS_DIM_1, COORDS, ISOUTOFBOUNDS, ARRIN_DIM_1, ARRIN_DIM_2, ARRIN, VAL) BIND(C)
    USE LANGEVIN_2D, ONLY: BILINEAR_INTERP
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: IDX_DIM_1
    INTEGER, INTENT(INOUT), DIMENSION(IDX_DIM_1) :: IDX
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: COORDS_DIM_1
    REAL(KIND=REAL64), INTENT(INOUT), DIMENSION(COORDS_DIM_1) :: COORDS
    LOGICAL, INTENT(INOUT) :: ISOUTOFBOUNDS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ARRIN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ARRIN_DIM_2
    REAL(KIND=REAL64), INTENT(INOUT), DIMENSION(ARRIN_DIM_1,ARRIN_DIM_2) :: ARRIN
    REAL(KIND=REAL64), INTENT(OUT) :: VAL
  
    CALL BILINEAR_INTERP(IDX, COORDS, ISOUTOFBOUNDS, ARRIN, VAL)
  END SUBROUTINE C_BILINEAR_INTERP
  

  
  SUBROUTINE C_INTERP_WRAPPER(COORDS_DIM_1, COORDS, ENEG, ENEGGRAD_DIM_1, ENEGGRAD, ENEGHESS_DIM_1, ENEGHESS, INVMET_DIM_1, INVMET,&
& INVMETGRAD_DIM_1, INVMETGRAD_DIM_2, INVMETGRAD, INVMETHESS_DIM_1, INVMETHESS_DIM_2, INVMETHESS, NECKVAL, ISOUTOFBOUNDS) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: INTERP_WRAPPER
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: COORDS_DIM_1
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(COORDS_DIM_1) :: COORDS
    REAL(KIND=REAL64), INTENT(OUT) :: ENEG
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ENEGGRAD_DIM_1
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(ENEGGRAD_DIM_1) :: ENEGGRAD
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ENEGHESS_DIM_1
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(ENEGHESS_DIM_1) :: ENEGHESS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMET_DIM_1
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(INVMET_DIM_1) :: INVMET
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETGRAD_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETGRAD_DIM_2
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(INVMETGRAD_DIM_1,INVMETGRAD_DIM_2) :: INVMETGRAD
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETHESS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INVMETHESS_DIM_2
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(INVMETHESS_DIM_1,INVMETHESS_DIM_2) :: INVMETHESS
    REAL(KIND=REAL64), INTENT(OUT) :: NECKVAL
    LOGICAL, INTENT(OUT) :: ISOUTOFBOUNDS
  
    CALL INTERP_WRAPPER(COORDS, ENEG, ENEGGRAD, ENEGHESS, INVMET, INVMETGRAD, INVMETHESS, NECKVAL, ISOUTOFBOUNDS)
  END SUBROUTINE C_INTERP_WRAPPER
  

  
  SUBROUTINE C_TIME_EVOLVE(COORDSIN_DIM_1, COORDSIN, ALLCOORDS_DIM_1, ALLCOORDS_DIM_2, ALLCOORDS, ALLMOMENTA_DIM_1, ALLMOMENTA_DIM_&
&2, ALLMOMENTA, LASTITER, FINISHEDSUCCESSFULLY) BIND(C)
    USE NORMAL
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE LANGEVIN_2D, ONLY: TIME_EVOLVE
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: COORDSIN_DIM_1
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(COORDSIN_DIM_1) :: COORDSIN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ALLCOORDS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ALLCOORDS_DIM_2
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(ALLCOORDS_DIM_1,ALLCOORDS_DIM_2) :: ALLCOORDS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ALLMOMENTA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: ALLMOMENTA_DIM_2
    REAL(KIND=REAL64), INTENT(OUT), DIMENSION(ALLMOMENTA_DIM_1,ALLMOMENTA_DIM_2) :: ALLMOMENTA
    INTEGER, INTENT(OUT) :: LASTITER
    LOGICAL, INTENT(OUT) :: FINISHEDSUCCESSFULLY
  
    CALL TIME_EVOLVE(COORDSIN, ALLCOORDS, ALLMOMENTA, LASTITER, FINISHEDSUCCESSFULLY)
  END SUBROUTINE C_TIME_EVOLVE
  

  
  SUBROUTINE C_RUN(INITIALCOORDS_DIM_1, INITIALCOORDS_DIM_2, INITIALCOORDS, SAVEPATHS, ALLCOORDS_DIM_1, ALLCOORDS_DIM_2, ALLCOORDS_&
&DIM_3, ALLCOORDS, ALLMOMENTA_DIM_1, ALLMOMENTA_DIM_2, ALLMOMENTA_DIM_3, ALLMOMENTA, LASTITER_DIM_1, LASTITER, FINISHEDSUCCESSFULLY&
&_DIM_1, FINISHEDSUCCESSFULLY) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE LANGEVIN_2D, ONLY: RUN
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INITIALCOORDS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: INITIALCOORDS_DIM_2
    REAL(KIND=REAL64), INTENT(IN), DIMENSION(INITIALCOORDS_DIM_1,INITIALCOORDS_DIM_2) :: INITIALCOORDS
    LOGICAL, INTENT(IN) :: SAVEPATHS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: ALLCOORDS_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: ALLCOORDS_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: ALLCOORDS_DIM_3
    REAL(KIND=REAL64), ALLOCATABLE, SAVE, DIMENSION(:,:,:) :: ALLCOORDS_LOCAL
    INTEGER(KIND=INT64), INTENT(OUT) :: ALLCOORDS
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: ALLMOMENTA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: ALLMOMENTA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: ALLMOMENTA_DIM_3
    REAL(KIND=REAL64), ALLOCATABLE, SAVE, DIMENSION(:,:,:) :: ALLMOMENTA_LOCAL
    INTEGER(KIND=INT64), INTENT(OUT) :: ALLMOMENTA
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: LASTITER_DIM_1
    INTEGER, ALLOCATABLE, SAVE, DIMENSION(:) :: LASTITER_LOCAL
    INTEGER(KIND=INT64), INTENT(OUT) :: LASTITER
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(OUT) :: FINISHEDSUCCESSFULLY_DIM_1
    LOGICAL, ALLOCATABLE, SAVE, DIMENSION(:) :: FINISHEDSUCCESSFULLY_LOCAL
    INTEGER(KIND=INT64), INTENT(OUT) :: FINISHEDSUCCESSFULLY
  
    CALL RUN(INITIALCOORDS, SAVEPATHS, ALLCOORDS_LOCAL, ALLMOMENTA_LOCAL, LASTITER_LOCAL, FINISHEDSUCCESSFULLY_LOCAL)
    
    ALLCOORDS_DIM_1 = SIZE(ALLCOORDS_LOCAL,1)
    ALLCOORDS_DIM_2 = SIZE(ALLCOORDS_LOCAL,2)
    ALLCOORDS_DIM_3 = SIZE(ALLCOORDS_LOCAL,3)
    ALLCOORDS = LOC(ALLCOORDS_LOCAL(1,1,1))
    
    ALLMOMENTA_DIM_1 = SIZE(ALLMOMENTA_LOCAL,1)
    ALLMOMENTA_DIM_2 = SIZE(ALLMOMENTA_LOCAL,2)
    ALLMOMENTA_DIM_3 = SIZE(ALLMOMENTA_LOCAL,3)
    ALLMOMENTA = LOC(ALLMOMENTA_LOCAL(1,1,1))
    
    LASTITER_DIM_1 = SIZE(LASTITER_LOCAL,1)
    LASTITER = LOC(LASTITER_LOCAL(1))
    
    FINISHEDSUCCESSFULLY_DIM_1 = SIZE(FINISHEDSUCCESSFULLY_LOCAL,1)
    FINISHEDSUCCESSFULLY = LOC(FINISHEDSUCCESSFULLY_LOCAL(1))
  END SUBROUTINE C_RUN
  
END MODULE C_LANGEVIN_2D

